### ISSUE TITLE
Remove #profile-content negative margins

### ISSUE THREAD

**Issue by adi130987** [unicef-polymer/etools-profile-dropdown#1] opened 2017-06-14 12:54 UTC
We need to remove #profile-content negative margins and maybe add a mixin in case we want to apply some styles on the working project. On PMP this negative margin makes the layout too big.

![screenshot from 2017-06-14 15 39 49](https://user-images.githubusercontent.com/1955740/27133052-9375edc4-5119-11e7-9aa7-ad250022e21c.png)

**Comment by marko911** [comment] 2017-06-14 14:01
Not sure how this has come up now, the styling hasn't changed from when this was hardcoded into the header instead of a bower component. In any case I will take a look at it.

**Comment by marko911** [comment] 2017-06-19 16:54
Closing this as the issue is with an app-theme mixin.

**Comment by adi130987** [comment] 2017-06-20 10:02
I do not think we communicated to well on this issue and most of this code was taken from PMP where this style had sense some time ago. So, I made some changes in PR #2.

There is no point using `overflow-y: auto` on `#profile-content`, it will generate 2 scrolls because `paper-dialog-scrollable` already has this. Also there was a negative margin on of -20px and then a padding of 15px that are not needed. The mixin from app-theme you mention only overwrites the `paper-dialog-scrollable` and not the `#profile-content`. I also added a mixin in case you need to apply style changes to this container. 

Please check my changes and let me know your thoughts.

**Comment by marko911** [comment] 2017-06-20 17:43
Yea, thats fine. Your changes work if we move the mixin for profile content to the app theme. But the paper-dialog-scrollable mixin DID remove the padding from `#profile-content` and then the neg margin pushed the text behind the borders which is why it displayed the way it did in PMP. So we need to make PR in all modules to add the new version of the profile dropdown and add the mixin to app theme to add a padding of 0 15px. @daniel-tabarcea Just a question regarding that style, why 15px? Isn't all padding like this in material design 16px?

**Comment by adi130987** [comment] 2017-06-21 08:20
I do not think that 15px padding has anything to do with material design :), but we should follow material design guidelines.

**Closed** 2017-06-21 13:55 UTC
Labels: bug
